version: '3.8'

services:
  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=docker
    ports:
      - "6379:6379"

  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=shortlinks
    ports:
      - "5432:5432"
